sudo: required
language: python
python:
- '3.7'
dist: xenial
before_install:
- openssl aes-256-cbc -K $encrypted_0e6f9bcfd0e0_key -iv $encrypted_0e6f9bcfd0e0_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
