sudo: required
language: python
python:
- '3.7'
dist: xenial
before_install:
- echo $TOKEN | gpg --passphrase-fd 0 credentials.tar.gz.gpg
- tar -xzf credentials.tar.gz
- rm credentials.tar.gz
install:
- pip install pipenv
- pipenv install --dev
script:
- pipenv run pytest --cov=./ --show-progress
- pipenv run coveralls
env:
  global:
    secure: hRlaAKAy8x6J0wZ8YUf81aszQS6NhNSJujIsZuqWmktb8oBXZTQaecSg7A3jRKOK9ccnKQdsBRF3+AFvxCRHwt1F90+87CnmNFJxAuru1CeMy/9m7FBtVblf+ntnFjGw9rqOL4qNA1Xok2ZUVtv2FuAkx+emS/10lIQEWQDtl/+4pbdAhbdgL9MPzzrb7Q2Idgcd1+1Ji4BPfpBB9HUIzmHB4W/9piVo4SJXG3flQnopy2Ycn6PtvxW3twOhgvY0Ut8hNWTfEL2qZmYvDZPh8EwjzEH8Rbx0ItAGxA4jafRfGcexqxYnV53fLeeMIy1VDu06YbA4NKHKPJvuS97SqV4rbnaI5fJQNgrLbfk+S4APTJe//c95UFUDYjKd1+YEnKpvmTvXgORz8LgF1O4wiBifGqAXL4JwnfTXD38z/twpCgk88NVI4yfxWDrMHmWwCTbzsMwAfncA8xYDunR/d4x6XX1Dz6CFPIuaBLHNyTqC0AoAJI1UV6VqU2lgS+u4giuboWYe5DKmJAzfwP6FfjWLln4ETrQYamaBwUHP5VvevJ5FbXyv8uLu1N77aAlv8NZDHZQciS4eDgenTtl5Z1HMeSU6APzTkfjigY7xUVSzHHTAg3tgzZG4gnecW6L1fXsfiproP4zXhACZxiZr39v4uggk/trSLtnm/IY4BYo=
