sudo: required

services:
  - docker

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - docker-compose up -d

language: python
python: 3.7
dist: xenial

install: 
  - make

jobs:
  include:
    - stage: test
      script: make test
    - stage: deploy
      if: branch = pending
      script: make deploy
