sudo: required
language: python
python:
- '3.7'
dist: xenial
services:
- docker
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
before_install:
- echo $TOKEN | gpg --passphrase-fd 0 credentials.tar.gz.gpg
- tar -xzf credentials.tar.gz
- rm credentials.tar.gz
install:
- pip install pipenv
- pipenv install --dev
script:
- pipenv run pytest --cov=./ --show-progress
- pipenv run coveralls
before_deploy:
- gcloud version || true
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export
  CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud version
- gcloud components install kubectl
- gcloud --quiet components update
deploy:
- provider: script
  script: chmod +x $TRAVIS_BUILD_DIR/k8s/deploy.sh && sh $TRAVIS_BUILD_DIR/k8s/deploy.sh
  skip_cleanup: true
  on:
    branch: swoldemi/master
env:
  global:
    secure: Jb+R8fLMq1mOIkRRAYTkOfahuAu+Hsn9PHl52vg5QD/CLT0/RG/ByNkft3loWQKedcCOf3KoihCYbFX21lINiBm4ta2fc4W3lb3JitIOwSu5y0friQ2SmQxNZksUNxwCuW9bAf5UXVrmn4vd7y2+nqgIR61oVW0JuupatU/liCUlfnpAzzm3ByxMizZh16G+Y9lRFUFIXzA/ipVkKXVujjnV7TJ1KAkWAWWMUkoOLOZD/kX1vIyQzmSQnE9YFJ8z3YDnKeySdlbxv/30mDXbmX5jyLlW+KVaX/SUzDwZE57OiBSfOZoi338ebXD4w5kGSbsgJIh7M20JMRduRJKzqaefYJWQffVkJykz2R9Aznp0J7yzevVoKIhvp2DaDaUWvaSfwby/ZvA2HTf5CejCmWtyvapfqXuc6sHGLaSx3+JTAlyPaepRgbNIyZuqNHzGo/fETBhSR/+y/jnOimk97ggVwPBUh/W6wVhs8HYhrcKradkPIqecNIs654EaXBQMeQ8T1lYvT8PjaiTtxnIjYLYP758UnOQblTCczbL/gkAYmavuS5b+q9xAkech32me08sxwhcKWzLyOC8zcU7KvDb61qrC1FWxLBVPicmKpmZtVb5BRZrYLgtRkfhNoI7HuvwvBY6hhd+J9DGPPD1IFUYaE6RwxRFKCJRiYfdFfAo=
