sudo: required
language: python
python:
- '3.7'
dist: xenial
before_install:
- echo $TOKEN | gpg --passphrase-fd 0 credentials.tar.gz.gpg
- tar -xzf credentials.tar.gz
- rm credentials.tar.gz
install:
- pip install pipenv
- pipenv install --dev
script:
- pipenv run pytest --cov=./ --show-progress
- pipenv run coveralls
env:
  global:
  - secure: u6XNC7dFIUFewG2ak8JWhElGTa7AiNWxkD8063+hLD2fhkr6jPWxqE/Q7lD4jXn4+RXeIKGU79FLfr4qTmb52HteQ+cHFzwQydsuAUySTPH7FWNrPu5lQ8/tkNwLOz3/d6kc3ZShWAGYEH9wmLBE6fva+O2EWMPcm05g72YikXeBAsTlczS8hCEk/2dEURb5O/a43RpgJstY6iT+6FNNCAeuRnZZcbQz9yyl5KjsiSW3TjOnFjGeefiR0dKFLNRHWa83vAJ1jWlsy84sMjNUinVDII/3jkyQxduWjcBq53e5Qpzk9yRkxDfRmwVsztAhn2aeycj1cTPm20++ZZl0jRKtnGnHbdtDVzQeALnrQTHo1rLl1D36qyBiiIDhiD/KAJinD1Ae5nmsHGyJD2EY/OS7ppHhbOKlsVX3dPsdeaW7pKPVoGBEbH7B1LkTWQNcjquyGHGJZ8e0pEKoLf8BsRJA4LgKN+7y4UCBiD3WjAEOSmU96JTEwFCi8Tqcv6gZOlZjqxV7XMBHcaRJgPVcwoRUoYYD4fyFKpHIuUFSyUQ1jtGqjgmJH5iOaxyVZRkOwhgRcavVlzhwOJnuY6H4Ob+Yyq6gyn5KgG7DVwVs+VQECy/1shQXdU6RrNjUAzRjWYARknHvjyBBE1fVfBTTivhq/m2zSTPz2i1kphn2TFY=
  - secure: Ed5I7ufi/97JokBSAjGksWC0jIxZLDkpCV07s64b5+QgyKS5NF50hwIVU+JAt+ZBgJqN3VkNqvtndg/CE/OvtG1hWOfftyFnDSh9osr1KOlwuRrus0wq6q9o/fhVkBLXWzfgxYEQvlzyCW/sBz4CyRWBL7DoLc7CqVu0zLHigY19PzDqFSo5KTk1EJS2gSbaIvGAtf4c0rWJRqESFFtCD3bQy/R8F0q4PwWKjOUKk57jIBHf4yQ46etDxHaDCA3i0/LXJ/Xp1xbFN1DMuFBNezmxGmS6WWUB0Gy1btgeBHWNnAQXZ2er6cOn5TxjwC+AsaSps+bVdcjY+qPyebgsGZtOQm8+PJJ2DVhNQhGGMdDCvAOa4uhcMcPB8IWGnGd9xK8GYyK3Raj6xidRQr7E9UdKS9IwiTeHZfQq8Df4ogiPzhSveBJ9/xks0zZYDylG7LT3pSRjIsk3jpsJCxbHbPg/d0Rty2UbMW8UrJPX5VOlKz9ffHOI9+oxYQpnp65IZfN8xJw83TGWyr8LmErbKRbKre0UWWnnti30xrsZIM/4nJ95B7mgm8zjalbdJrquAkwEEN5k5+IndBPHaklY4ZVB4Xsow+YurpdTcZHBcImmKNNjFoOWBf9MS6EIrJH/Duu0/qZpjAiIkRLfjiYp4e3oQIfUcWUFMtrOeWHTiHA=
