sudo: required
language: python
python:
- '3.7'
dist: xenial
before_install:
- echo $TOKEN | gpg --passphrase-fd 0 credentials.tar.gz.gpg
- tar -xzf credentials.tar.gz
- rm credentials.tar.gz
install:
- pip install pipenv
- pipenv install --dev
script:
- pipenv run pytest --cov=./ --show-progress
- pipenv run coveralls
env:
  global:
  - secure: Ed5I7ufi/97JokBSAjGksWC0jIxZLDkpCV07s64b5+QgyKS5NF50hwIVU+JAt+ZBgJqN3VkNqvtndg/CE/OvtG1hWOfftyFnDSh9osr1KOlwuRrus0wq6q9o/fhVkBLXWzfgxYEQvlzyCW/sBz4CyRWBL7DoLc7CqVu0zLHigY19PzDqFSo5KTk1EJS2gSbaIvGAtf4c0rWJRqESFFtCD3bQy/R8F0q4PwWKjOUKk57jIBHf4yQ46etDxHaDCA3i0/LXJ/Xp1xbFN1DMuFBNezmxGmS6WWUB0Gy1btgeBHWNnAQXZ2er6cOn5TxjwC+AsaSps+bVdcjY+qPyebgsGZtOQm8+PJJ2DVhNQhGGMdDCvAOa4uhcMcPB8IWGnGd9xK8GYyK3Raj6xidRQr7E9UdKS9IwiTeHZfQq8Df4ogiPzhSveBJ9/xks0zZYDylG7LT3pSRjIsk3jpsJCxbHbPg/d0Rty2UbMW8UrJPX5VOlKz9ffHOI9+oxYQpnp65IZfN8xJw83TGWyr8LmErbKRbKre0UWWnnti30xrsZIM/4nJ95B7mgm8zjalbdJrquAkwEEN5k5+IndBPHaklY4ZVB4Xsow+YurpdTcZHBcImmKNNjFoOWBf9MS6EIrJH/Duu0/qZpjAiIkRLfjiYp4e3oQIfUcWUFMtrOeWHTiHA=
