sudo: required

services:
  - docker

before_install:
  - docker-compose up -d

language: python
python: 3.7
dist: xenial

install: 
  - make

jobs:
  include:
    - stage: test
      script: make test
    - stage: deploy
      if: branch = pending
      script: make deploy
